[package]
name = "taskmr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.27.0", features = ["bundled"] }
clap = { version = "3.1.6", features = ["derive"] }
tabwriter = "1"
anyhow = "1.0"
dirs = "4.0"
