name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: check to publish
    runs-on: ubuntu-latest
    outputs:
      shoud-skip-publish: ${{ steps.versioning.conclusion }}
    steps:
    - uses: actions/checkout@v2
    - name: Versioning
      id: versioning
      continue-on-error: true
      run: |
          VERSION=$(cat Cargo.toml | grep -m 1 "version =" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          echo ::set-output name=version::$VERSION
          git fetch --prune --unshallow
          git tag show $VERSION
    - name: Tag
      id: tag_version
      if: failure()
      uses: mathieudutour/github-tag-action@v5.2
      with:
        custom_tag: ${{ steps.versioning.outputs.version }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: rust test
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.should-skip-publish == 'failure'
    steps:
    - uses: actions/checkout@v2
    - name: Login
      env:
        CRATE_IO_TOKEN: ${{ secrets.CRATE_IO_TOKEN }}
      run: cargo login "$CRATE_IO_TOKEN"
    - name: Publish
      run: cargo publish
