name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: check to publish
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.versioning.outputs.should_publish }}
    steps:
    - uses: actions/checkout@v2
    - name: Versioning
      id: versioning
      run: |
          VERSION=$(cat Cargo.toml | grep -m 1 "version =" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          echo ::set-output name=version::$VERSION
          git fetch --prune --unshallow
          git tag show v$VERSION || if [ $? -eq 0 ]; then SHOULD_PUBLISH='false'; else SHOULD_PUBLISH='true'; fi
          echo ::set-output name=should_publish::$SHOULD_PUBLISH
    - name: Tag
      id: tag_version
      if: steps.versioning.outputs.should_publish == 'true'
      uses: mathieudutour/github-tag-action@v5.2
      with:
        custom_tag: ${{ steps.versioning.outputs.version }}
        github_token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: publish taskmr
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.should_publish == 'true'
    steps:
    - uses: actions/checkout@v2
    - name: Login
      env:
        CRATE_IO_TOKEN: ${{ secrets.CRATE_IO_TOKEN }}
      run: cargo login "$CRATE_IO_TOKEN"
    - name: Publish
      run: cargo publish
